image: "node:6.9.1"

variables:
  NPM_CONFIG_LOGLEVEL: warn

cache:
  paths:
    - node_modules

stages:
  - test
  - release
  - deploy


build:
  stage: test
  script:
    - npm install
    - npm run build


release:
  image: "gitlab/dind:latest"
  stage: release
  only:
    - master
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t cowhub/cowhub-web-frontend:latest .
    - docker push cowhub/cowhub-web-frontend


deploy:
  stage: deploy
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
    - rm -rf .ssh/known_hosts
    - npm install
    - npm run build
    - npm run tar
    - cp public/index.html dist/
    - rsync -avz deploy.sh -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/
    - rsync -avz dist.tar.gz -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/
    - ssh root@cloud-vm-46-70.doc.ic.ac.uk "/bin/bash -c /deploy.sh"
