image: "node:6.9.1"

variables:
  NODE_ENV: test

cache:
  paths:
    - node_modules

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
  - rm -rf .ssh/known_hosts
  - node --version
  - npm install

build:
  script:
    - npm run build

deploy:
  only:
    - feature/docker_deploy
  script:
    - npm run build
    - cp public/index.html dist/
    - rsync -avz deploy.sh -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/app
    - rsync -avz dist/* -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/app --delete
    - ssh root@cloud-vm-46-70.doc.ic.ac.uk "/bin/bash -c /app/deploy.sh"
