image: "node:6.9.1"

variables:
  NODE_ENV: test
  NPM_CONFIG_LOGLEVEL: warn

cache:
  paths:
    - node_modules

stages:
  - test
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
  - rm -rf .ssh/known_hosts
  - node --version
  - npm install

build:
  stage: test
  script:
    - npm run build

deploy:
  stage: deploy
  only:
    - master
  script:
    - sed -i -e 's/localhost:3000/\'cloud-vm-46-166\.doc\.ic\.ac\.uk\'/g' dev/**/*
    - npm run build
    - cp public/index.html dist/
    - rsync -avz deploy.sh -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/
    - rsync -avz dist.tar.gz -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-70.doc.ic.ac.uk:/
    - ssh root@cloud-vm-46-70.doc.ic.ac.uk "/bin/bash -c /deploy.sh"
