version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgres/data
  api:
    image: cowhub/cowhub-server-api
    command: /bin/bash -c 'bundle exec rake db:setup && bundle exec rails server -b 0.0.0.0 -p 8080'
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
  web:
    build: .
    command: /bin/bash -c '/root/.yarn/bin/yarn install && /root/.yarn/bin/yarn run dev'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
