version: '2'

services:
  db:
    image: postgres
  api:
    image: cowhub/cowhub-server-api
    depends_on:
      - db
  web:
    build: .
    command: /bin/bash -c 'npm install && npm run dev'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
